server:
  port: 8282

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/salary
    username: postgres
    password: Raja@nagar08
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  application:
    name: SALARY-SERVICE

  config:
    import: configserver:http://localhost:8484

#  eureka:
#    instance:
#      prefer-ip-address: true
#    client:
#      fetch-registry: true
#      register-with-eureka: true
#      service-url:
#        defaultZone: http://localhost:8761/eureka
#


